[mpv]
fetch.github = "mpv-player/mpv"
src.git = "https://github.com/mpv-player/mpv.git"

[mpv-config]
fetch.github = "dyphire/mpv-config"
src.git = "https://github.com/dyphire/mpv-config.git"

[mpv-omniphony]
fetch.github = "mgth/mpv-omniphony"
src.git = "https://github.com/mgth/mpv-omniphony.git"

[mpv-sockets]
fetch.github = "wis/mpvSockets"
src.git = "https://github.com/wis/mpvSockets.git"

[nvidia-patch]
fetch.github = "keylase/nvidia-patch"
src.git = "https://github.com/keylase/nvidia-patch.git"

[oh-my-rime]
fetch.github = "Mintimate/oh-my-rime"
src.git = "https://github.com/Mintimate/oh-my-rime.git"

[rime-custom-pinyin-dictionary]
fetch.url = "https://github.com/Renna42/CustomPinyinDictionary_txt/releases/download/$ver/CustomPinyinDictionary_Fcitx.txt"
src.github = "Renna42/CustomPinyinDictionary_txt"

[rime-moetype]
fetch.url = "https://github.com/suiginko/moetype/releases/download/$ver/moe.dict.yaml"
src.github = "suiginko/moetype"

[rime-zhwiki]
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.3.0/zhwiki-$ver.dict.yaml"
src.webpage = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/expanded_assets/0.3.0"
src.regex = "zhwiki-([0-9]{8})\\.dict\\.yaml"
