# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mpv-sockets = {
    pname = "mpv-sockets";
    version = "3b3f430074a67c63572a582847ed1fa69330c668";
    src = fetchFromGitHub {
      owner = "wis";
      repo = "mpvSockets";
      rev = "3b3f430074a67c63572a582847ed1fa69330c668";
      fetchSubmodules = false;
      sha256 = "sha256-KFv3imLuiV+APx4A8TSi2LXL5gdHNKc497fRwBubvMk=";
    };
    date = "2024-02-13";
  };
  nvidia-patch = {
    pname = "nvidia-patch";
    version = "80e48e9346beb9407734a090d33c5e79e9113b01";
    src = fetchFromGitHub {
      owner = "keylase";
      repo = "nvidia-patch";
      rev = "80e48e9346beb9407734a090d33c5e79e9113b01";
      fetchSubmodules = false;
      sha256 = "sha256-Lc7XJRWbrzR6c2x8enGHKCJ1hh0NE9cBOgbuoWBBF2Q=";
    };
    date = "2026-04-03";
  };
  oh-my-rime = {
    pname = "oh-my-rime";
    version = "3aa2ba7278d4116f2a388bbd263e4d2cbeea8f1b";
    src = fetchFromGitHub {
      owner = "Mintimate";
      repo = "oh-my-rime";
      rev = "3aa2ba7278d4116f2a388bbd263e4d2cbeea8f1b";
      fetchSubmodules = false;
      sha256 = "sha256-9HLfYqiqFQfEmu0fcCpTv5Ezk1J00wlHgNG918vAOiM=";
    };
    date = "2026-04-13";
  };
  rime-moetype = {
    pname = "rime-moetype";
    version = "20260314";
    src = fetchurl {
      url = "https://github.com/suiginko/moetype/releases/download/20260314/tone_moe.dict.yaml";
      sha256 = "sha256-qfm1Iq0+8ZdrSebaDQcNacnCZVr4sHvLlzBIyRfI9/k=";
    };
  };
  rime-zhwiki = {
    pname = "rime-zhwiki";
    version = "20260416";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.3.0/zhwiki-20260416.dict.yaml";
      sha256 = "sha256-XBQORi+cAKEZUAt/7A07kn8Pg5IAAafqQI4mdI0J6gc=";
    };
  };
}
