# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mpv-sockets = {
    pname = "mpv-sockets";
    version = "3b3f430074a67c63572a582847ed1fa69330c668";
    src = fetchFromGitHub {
      owner = "wis";
      repo = "mpvSockets";
      rev = "3b3f430074a67c63572a582847ed1fa69330c668";
      fetchSubmodules = false;
      sha256 = "sha256-KFv3imLuiV+APx4A8TSi2LXL5gdHNKc497fRwBubvMk=";
    };
    date = "2024-02-13";
  };
  nvidia-patch = {
    pname = "nvidia-patch";
    version = "ad462e42c97fea52c0d58ce0507fe6dc36da675b";
    src = fetchFromGitHub {
      owner = "keylase";
      repo = "nvidia-patch";
      rev = "ad462e42c97fea52c0d58ce0507fe6dc36da675b";
      fetchSubmodules = false;
      sha256 = "sha256-3qoGL7/S6W47fZfSr20giiFxXisdLQ323le38iQIJMI=";
    };
    date = "2026-07-13";
  };
  oh-my-rime = {
    pname = "oh-my-rime";
    version = "99bb172709d2f51146eca6d3860107f0ebfa145a";
    src = fetchFromGitHub {
      owner = "Mintimate";
      repo = "oh-my-rime";
      rev = "99bb172709d2f51146eca6d3860107f0ebfa145a";
      fetchSubmodules = false;
      sha256 = "sha256-itbEBukcBR1l7l2GnGiuN9bqCSe4iF1y9XimJ+TjFaA=";
    };
    date = "2026-07-15";
  };
  rime-custom-pinyin-dictionary = {
    pname = "rime-custom-pinyin-dictionary";
    version = "v20260101";
    src = fetchurl {
      url = "https://github.com/Renna42/CustomPinyinDictionary_txt/releases/download/v20260101/CustomPinyinDictionary_Fcitx.txt";
      sha256 = "sha256-OozcuETRrl9dq5djuK0gd6iMS5CydLvbavayKjBJcqg=";
    };
  };
  rime-moetype = {
    pname = "rime-moetype";
    version = "20260517";
    src = fetchurl {
      url = "https://github.com/suiginko/moetype/releases/download/20260517/tone_moe.dict.yaml";
      sha256 = "sha256-zl7PHyTj3rFDC4ttZMA3z9nn6XtayINfqqLp5mNbWUY=";
    };
  };
  rime-zhwiki = {
    pname = "rime-zhwiki";
    version = "20260416";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.3.0/zhwiki-20260416.dict.yaml";
      sha256 = "sha256-XBQORi+cAKEZUAt/7A07kn8Pg5IAAafqQI4mdI0J6gc=";
    };
  };
}
